### ISSUE TITLE
No arb files found

### ISSUE THREAD

**Issue by navneet-singh-github** [lsaudon/l10nization#157]
Getting "No arb files found" message in vs-code while extracting string.

**Directory structure**
<img width="311" alt="Screenshot 2023-04-20 at 2 57 22 PM" src="https://user-images.githubusercontent.com/94953723/233323171-3ebb8c8f-de10-45af-a538-f0a66f1aeadc.png">

**l10n.yaml file**
<img width="479" alt="Screenshot 2023-04-20 at 2 57 40 PM" src="https://user-images.githubusercontent.com/94953723/233323177-9ea6b92b-2be8-4c54-8a8a-d076a29d94a3.png">

**and local file**
<img width="501" alt="Screenshot 2023-04-20 at 2 58 04 PM" src="https://user-images.githubusercontent.com/94953723/233323183-55ef2d36-2911-43f1-933e-678b96e5d060.png">

**Comment by lsaudon** [comment]
Thanks for your feedback @navneet-singh-github.

Quick fix: If it doesn't impact your project too much. Can you put the arbs files in an `lib/core/l10n/arb` folder?

As soon as I have time, I will correct this problem.

**Comment by lsaudon** [comment]
In your `l10n.yaml` replace `lib/core/l10n/` to `lib/core/l10n`.

**Comment by navneet-singh-github** [comment]
After doing this I'm not getting error but nothing happens now. Only enter variable name prompt open.

**Comment by lsaudon** [comment]
After entering the desired variable name and type (Like a GIF in README).
Doesn't it add to the arbs files?

**Comment by navneet-singh-github** [comment]
Only enter variable name prompt opens; nothing happens after entering the variable name. It does not add to arbs files also.

**Comment by lsaudon** [comment]
If it's not a problem, you can copy and paste the text you want to extract.

**Comment by lsaudon** [comment]
I think I've found the problem.
It's when you have several variables.
I'll try to fix it as soon as possible.

**Comment by lsaudon** [comment]
I push a new version 1.4.0 tell me if this fix your problem.
@navneet-singh-github
