### ISSUE TITLE
[Idea] Support for adding metadata of the message

### ISSUE THREAD

**Issue by milindgoel15** [lsaudon/l10nization#187]
When we extract a string into an arb file, it asks for what ID we want to give to the string. Can you also add another input for adding metadata where we can add a description for it to give its context?

**Comment by lsaudon** [comment]
Hi @milindgoel15,
Thanks for the idea.
Can you give me an example.

**Comment by milindgoel15** [comment]
When we use the extract to arb function to add a string to arb and use that to localize, there comes an input box to give an identifier,
![image](https://github.com/lsaudon/l10nization/assets/45682747/193d6617-eade-491d-9737-c4e316e2c6d7)

After entering, it shows another input box to add a context description to it.
