### ISSUE TITLE
Add possibility to disable sorting after extracting a value

### ISSUE THREAD

**Issue by mrRedSun** [lsaudon/l10nization#214]
Currently, when extracting a value sorting happens automatically which is not desirable in my use case, please add a flag to disable auto sorting.

Great extension by the way, saved me a lot of time on a recent refactoring ❤️

**Comment by mrRedSun** [comment]
My bad, it wasn't sorting them, but just formatted a file

**Comment by lsaudon** [comment]
You can disable the sort with `l10nization.arbSort` settings

**Comment by lsaudon** [comment]
@mrRedSun I also made this [plugin](https://pub.dev/packages/l10nization_cli) that detects unused translations in the application.

**Comment by mrRedSun** [comment]
Oh damn, definitely have too many of those, gonna check it out 😅
