### ISSUE TITLE
Error: Undefined name 'l10n'

### ISSUE THREAD

**Issue by vietstone-ng** [lsaudon/l10nization#218]
Hello, I get this error. I think I miss some configuration. How can I correct it? Thank you
> Undefined name 'l10n'.
> Try correcting the name to one that is defined, or defining the name.

**Comment by vietstone-ng** [comment]
Oh, I see your `l10nization_cli`, then I know how it work. It'd be nice if having some docs in README

**Comment by lsaudon** [comment]
> Hello, I get this error. I think I miss some configuration. How can I correct it? Thank you
> 
> > Undefined name 'l10n'.
> > Try correcting the name to one that is defined, or defining the name.

Do you use l10n, r13n or i18n?
When did you make the mistake?

**Comment by lsaudon** [comment]
> `l10nization_cli`

l10nization check-unused my_app
