### ISSUE TITLE
Setting to disable description prompt

### ISSUE THREAD

**Issue by RobertOdrowaz** [lsaudon/l10nization#239]
I believe a lot of people (me included) don't feel the need to provide description for terms. Especially since this tool is used to edit arbs directly and thus probably is used mostly by technical people who can look up necessary context in the code. Having an option to disable the description prompt would be nice.

I will implement it and pull request when I have some time

**Comment by lsaudon** [comment]
It already exists.
https://github.com/lsaudon/l10nization#add-description

**Comment by lsaudon** [comment]
Can you confirm that when the parameter is false? We don't have the description.

**Comment by RobertOdrowaz** [comment]
Yes, there is no description input when this settings is disabled. I must have missed this option somehow

**Comment by lsaudon** [comment]
Probably very badly named 😂
Do you have a better name?
