### ISSUE TITLE
No arb files found in the project

### ISSUE THREAD

**Issue by mrRedSun** [lsaudon/l10nization#245]
<img width="385" alt="image" src="https://github.com/lsaudon/l10nization/assets/22750848/18ccfc50-d9a5-4e6c-bd79-f0a152af1395">

My settings
<img width="759" alt="image" src="https://github.com/lsaudon/l10nization/assets/22750848/f5b12941-8d7b-4c66-8d3d-3f5ab0ed5467">

My project structure:
l10n.yaml in the root
`arb-dir: ./lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
nullable-getter: false
untranslated-messages-file: to_be_translated.json
`

**Comment by mrRedSun** [comment]
After arb dir changed to lib/l10n, started working

**Comment by lsaudon** [comment]
Replace arb-dir: ./lib/l10n to arb-dir: /lib/l10n

**Comment by mrRedSun** [comment]
/lib/l10n wouldn't work with flutter as / refers to root of file system

I think there's still something wrong with how path is parsed because ./ and nothing are equivalent
