### ISSUE TITLE
Handle single quotes better.

### ISSUE THREAD

**Issue by sgehrman** [lsaudon/l10nization#378]
```
I use single quotes, so I have some strings like 'This is John\'s stuff'
```

Converting that to double quotes makes it better, but it would be nice if your code worked better.
```
'This is John\'s stuff'  => "This is John\\'s stuff"
```
but using double quotes in my code:
```
"This is John's stuff" => "This is John's stuff"
```
Also in the app_localizations.dart files you get 
```
'This is John\\\'s stuff'
```
 It would be good if you could not do the \\ and just use the ' with double quotes

Small thing, but it looks much cleaner, and I don't want to have to convert to double quotes to get the cleaner version.

**Comment by sgehrman** [comment]
I'm just converting the string to double quotes before adding to arb, so not a big deal, just a suggestion.

**Comment by lsaudon** [comment]
Hi @sgehrman, i make this #383.
Is it what you imagined?
I replace `\\'` with `'`.
The problem I see is that if someone really wants to `\\'` it will be replaced.

**Comment by lsaudon** [comment]
The feature is present in version 3.2.0
