### ISSUE TITLE
yaml file not found

### ISSUE THREAD

**Issue by launay12u** [lsaudon/l10nization#39]
Thanks for this extension, however I can't use it.

When I want to use the extension on a text in my code I always get the error: The l10n.yaml file was not found. However my yaml file is called l10n.yaml and is at the root of my flutter project (see screenshot). I didn't change any parameter of the extension.

PS : I am on Mac (I don't know if the paths are different)

Thanks in advance for the answer.
![Screenshot 2022-12-01 at 1 48 10 PM](https://user-images.githubusercontent.com/18292489/205056915-fbf67546-0ee3-4637-a058-c765089da664.png)

**Comment by lsaudon** [comment]
Thanks for reporting this bug.
I am also on macOS.
I'll look into it as soon as possible.

**Comment by lsaudon** [comment]
The bug is fixed in version 1.0.1.
Thanks for reporting it.

**Comment by launay12u** [comment]
Thanks for the reactivity :D
