### ISSUE TITLE
Option to add messages only to template ARB file

### ISSUE THREAD

**Issue by RobertOdrowaz** [lsaudon/l10nization#400]
Option to add new messages only to template file would be great. Currently new messages are added to all ARB files which makes it hard to tell that they still require translation. This is especially a problem when using `arb_translate` for automatic translation.

I can make a PR with this feature when I have some free time.

**Comment by lsaudon** [comment]
Hi @RobertOdrowaz,

Thanks for issue.

You want

app_en.arb
```json
{
  "@@locale": "en",
  "helloWorld": "Hello World"
}
```

app_es.arb
```json
{
  "@@locale": "es",
  "helloWorld": ""
}
```

or

app_en.arb
```json
{
  "@@locale": "en",
  "helloWorld": "Hello World"
}
```

app_es.arb
```json
{
  "@@locale": "es"
}
```

**Comment by RobertOdrowaz** [comment]
I would prefer the second option without the entry at all. This way `arb_trnaslate` would work correctly and l10n-gen would also correctly warn about missing translations. But I think there can be three options available:
1. Add in template language
2. Add empty
3. Don't add

**Comment by lsaudon** [comment]
Okay for an enumeration, but for the moment we only manage:
Add
Don't add

**Comment by lsaudon** [comment]
The feature is present in version 3.2.0

**Comment by RobertOdrowaz** [comment]
@lsaudon Thanks a lot! I got back to this issue for a different reason (unrelated to `arb_translate`) so I'm very glad it has been resolved
